###############################################################################
# OFFICE - Room State Management
# States: Available, DnD (Do Not Disturb), Off
###############################################################################

input_select:
  office_state:
    name: "Office State"
    options:
      - Available
      - DnD
      - "Off"
    initial: Available
    icon: mdi:desk

automation:
  ###########################################################################
  # OFFICE STATE: DnD
  # No TTS, red indicator light outside office
  ###########################################################################
  - id: office_state_dnd
    alias: "Office - State DnD"
    trigger:
      - platform: state
        entity_id: input_select.office_state
        to: "DnD"
    action:
      # Turn on a coloured indicator (if you have one outside office)
      # For now, set office spotlights to a warmer dim
      - service: light.turn_on
        target:
          entity_id: light.office_spotlights
        data:
          brightness_pct: 40
          color_temp_kelvin: 2700

  - id: office_state_available
    alias: "Office - State Available"
    trigger:
      - platform: state
        entity_id: input_select.office_state
        to: "Available"
    action:
      - service: light.turn_on
        target:
          entity_id: light.office_spotlights
        data:
          brightness_pct: 100
          color_temp_kelvin: 4000

  - id: office_state_off
    alias: "Office - State Off"
    trigger:
      - platform: state
        entity_id: input_select.office_state
        to: "Off"
    action:
      - service: light.turn_off
        target:
          entity_id: light.office_spotlights

  ###########################################################################
  # EXISTING: Motion-based lighting
  ###########################################################################
  - id: office_lights_motion_on
    alias: "Office - Motion Lights On"
    trigger:
      - platform: state
        entity_id: binary_sensor.office_motion_sensor_occupancy
        to: "on"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.office_state
            state: "Off"
      - condition: state
        entity_id: input_boolean.lighting_automations
        state: "on"
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: 10
    action:
      - service: light.turn_on
        target:
          entity_id: light.office_spotlights
        data:
          brightness_pct: >
            {% if states('input_select.office_state') == 'DnD' %}
              40
            {% else %}
              100
            {% endif %}

  - id: office_lights_motion_off
    alias: "Office - Motion Lights Off"
    trigger:
      - platform: state
        entity_id: binary_sensor.office_motion_sensor_occupancy
        to: "off"
        for:
          minutes: 15
    condition:
      - condition: state
        entity_id: input_select.office_state
        state: "Available"
      - condition: state
        entity_id: input_boolean.lighting_automations
        state: "on"
    action:
      - service: light.turn_off
        target:
          entity_id: light.office_spotlights
